# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wuming/code/orm_playground/thirdparties/fmt/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wuming/code/orm_playground/thirdparties/fmt/support/cmake/JoinPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeParseArguments.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCXXCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCXXSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckFlagCommonConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))

/Users/wuming/code/orm_playground/xcode_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/wuming/code/orm_playground -B/Users/wuming/code/orm_playground/xcode_build
