# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wuming/code/orm_playground/thirdparties/sqlite3/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/wuming/code/orm_playground/thirdparties/sqlite3/sqlite3_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/GNUInstallDirs.cmake))

/Users/wuming/code/orm_playground/xcode_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/wuming/code/orm_playground -B/Users/wuming/code/orm_playground/xcode_build
